device: 1

decl:
  train: 'data/KorNLI/kornli_train.pkl'
  valid: 'data/KorNLI/kornli_valid.pkl'
  test: 'data/KorNLI/kornli_test.pkl'

poem:
  train: 'poem_output/poem_train.pkl'
  valid: 'poem_output/poem_valid.pkl'
  test: 'poem_output/poem_test.pkl'

vocab_path: 'data/concat/kornli_poem_vocab.json'
output_dir: 'classifier_output'
model_path: 'classifier_balance.pt'

token:
  pad_token: 0
  oov_token: 1
  start_token: 2
  end_token: 3

max_len: 17
max_vocab: 10000
batch_size: 256
emb_size: 100
filter: 400
kernel: 3

lr: 0.0005
mu: 0.5
nu: 0.999